# Name of your blog (this will show up in the RSS feed)
name: Empathy Lab

# Short description (will also be used in the RSS feed)
description: Empathy Lab Internal Documentation

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://2012mtb.empathylab.com

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true


#lsi: true

rebuild_thumbs: false

jekyll_sort:
  - src: posts
    by: sort
    direction: up
    dest: promoted_by_sort
    include_tags:
    - promoted

  - src: pages
    by: sort
    direction: down
    dest: section_by_sort
    include_tags:
    - section
